### ISSUE TITLE
Conditional Validation Using IValidatableObject

### ISSUE THREAD

**Issue by ryanbuening** [saad749/BeginCollectionItemCore#10]
I'm using BeginCollectionItem and I need to require a field in my collection depending on the value of another field in my collection. I tried using the built-in [IValidatableObject ](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation)on my class like so:

```
public class MyViewModel : IValidatableObject
{
	public List<MyCollection> MyCollection { get; set; } = new List<MyCollection>();

	public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
	{
		foreach (var item in MyCollection)
		{
			if (item.Id == null)
			{
				yield return new ValidationResult("Name is required", new[] { "Name" });
			}
		}
	}
}
```
This logic runs correctly and returns an error if the condition is met, however, the error message is not displayed on the field. Is there a way to make this work or am I going about this the wrong way?

**Comment by saad749** [comment]
If I understand correctly, It will depend on how you are trying to display the validation results and might want to look into validation tag helpers: http://www.davepaquette.com/archive/2015/05/14/mvc6-validation-tag-helpers-deep-dive.aspx .

**Comment by ryanbuening** [comment]
I have a validation helper on my view for the "Name" field. I'll try to create a GitHub repo in the next few days that shows my example.

**Comment by ryanbuening** [comment]
@saad749 I created an example of what I'm trying to do here: https://github.com/ryanbuening/DynamicCollections

Anyone have any ideas? Thanks.

**Comment by ryanbuening** [comment]
Disregard. If I put the IValidatableObject on MyCollection instead of MyViewModel it works.
