### ISSUE TITLE
Nested Collections

### ISSUE THREAD

**Issue by phobos04** [saad749/BeginCollectionItemCore#3]
Hi,
please is there any documentation related to the "nested collections" feature?
Nested items from the initial ViewModel are correctly displayed and posted back, but newly added children are not.
Looking at the generated HTML it appears that the newly added inner children are not decorated with any reference to their parent.
Please, how shoud I solve this issue?
Thanks

**Comment by saad749** [comment]
I was able to reproduce the issue, but don't have time to fix it this week. Any PR with the fix is appreciated.

**Comment by saad749** [comment]
Fixed by 8d8f692996bd118f2b25bb136c24420f1e1e8045 in Version 1.0.7
