### ISSUE TITLE
ASP MVC 5 version

### ISSUE THREAD

**Issue by weedkiller** [saad749/BeginCollectionItemCore#4]
Hi, can you also provide an ASP MVC 5 version, theres is one out there but it makes a round trip on every row add.

Thanks

**Comment by saad749** [comment]
This version is a fork of original version : https://www.nuget.org/packages/BeginCollectionItem/ which should work with ASP.Net MVC 5.

Both, this and the original version will make round trip for every row. Consider using jquery to add rows, if you don't wish to make the round trip, or frameworks like angular2 can provide easier solutions.

**Comment by weedkiller** [comment]
If you do not plan on supporting it, just say so!

The other version is not ASP MVC 5  but MVC 2  from 2012 over 5 yrs old.

**Comment by saad749** [comment]
Have you tried using it with ASP.Net MVC 5? if the other version is not working with ASP.Net MVC 5, I can look into it. As far as I understand, it will work from ASP.Net MVC 2 to ASP.Net MVC 5.
